#!/bin/bash

# Script to remove dead code files identified by knip
# Generated on 2025-10-02

set -e

echo "Removing dead code files..."

# API routes that are deleted from git already
rm -f "app/(communication)/api/roleplay-partner/tools.ts"
rm -f "app/(learning)/api/reading/generate-questions/test-route.ts"

# Unused components
rm -f "app/(learning)/lessons/lessons-list.tsx"
rm -f "app/(learning)/lessons/page-server.tsx"
rm -f "app/components/AgentMultibandAudioVisualizer.tsx"
rm -f "app/components/audio_chat/AudioChatAgentMultibandAudioVisualizer.tsx"
rm -f "app/components/audio_chat/AudioChatFullscreenAudioChat.tsx"
rm -f "app/components/audio_chat/AudioChatFullscreenTranscriptionTile.tsx"
rm -f "app/components/audio_chat/AudioChatLessonContainer.tsx"
rm -f "app/components/audio_chat/AudioChatLessonContainerV2.tsx"
rm -f "app/components/audio_chat/AudioChatMatchingGridExercise.tsx"
rm -f "app/components/audio_chat/AudioChatSentenceBuilder.tsx"
rm -f "app/components/audio_chat/SimpleTranscriptionTile.tsx"
rm -f "app/components/audio-chat-components/AudioChatColorCodedText.tsx"
rm -f "app/components/audio-chat-components/AudioChatMatchingExercise.tsx"
rm -f "app/components/audio-chat-components/AudioChatMemoryMatching.tsx"
rm -f "app/components/audio-chat-components/AudioChatSentenceBuilder.tsx"
rm -f "app/components/audio-chat-components/AudioChatTable.tsx"
rm -f "app/components/AudioChatVisualizer.tsx"
rm -f "app/components/ChatMessage.tsx"
rm -f "app/components/ChatMessageInput.tsx"
rm -f "app/components/ChatTile.tsx"
rm -f "app/components/CloseIcon.tsx"
rm -f "app/components/CompactMatchingExercise.tsx"
rm -f "app/components/ConnectivityIndicator.tsx"
rm -f "app/components/FullscreenAudioChat.tsx"
rm -f "app/components/FullscreenTranscriptionTile.tsx"
rm -f "app/components/LowConnectivityNotification.tsx"
rm -f "app/components/mobile/AudioChatVisualizer.tsx"
rm -f "app/components/mobile/FillInBlank.tsx"
rm -f "app/components/mobile/FixedMatchingExercise.tsx"
rm -f "app/components/mobile/Flashcard.tsx"
rm -f "app/components/mobile/MatchingExercise.tsx"
rm -f "app/components/mobile/MobileMatchingGrid.tsx"
rm -f "app/components/mobile/SentenceBuilder.tsx"
rm -f "app/components/mobile/TimedMatchingExercise.tsx"
rm -f "app/components/mobile/WordTransition.tsx"
rm -f "app/components/NoAgentNotification.tsx"
rm -f "app/components/pronunciation/audio-player.tsx"
rm -f "app/components/simple-pronunciation-practice.tsx"
rm -f "app/components/TranscriptionTile.tsx"
rm -f "app/components/TranscriptionView.tsx"
rm -f "app/components/TypewriterText.tsx"
rm -f "app/components/ui/progress-bar.tsx"
rm -f "app/data/placementTestData.ts"
rm -f "app/hooks/useDevice.ts"
rm -f "app/hooks/useTrackVolume.ts"
rm -f "app/page.backup.tsx"
rm -f "app/utils/deviceDetection.ts"
rm -f "app/utils/geminiAi.ts"
rm -f "app/utils/supabaseClient.ts"

rm -f "components/admin/UserRoleManager.tsx"
rm -f "components/AIGrammarConjugator.tsx"
rm -f "components/CallToActionSection.tsx"
rm -f "components/chat/ChatLayout.tsx"
rm -f "components/chat/TypewriterText.tsx"
rm -f "components/chatbot/ChatbotConfigManager.ts"
rm -f "components/ColorCodedText.tsx"
rm -f "components/courses/ExamTypeSelection.tsx"
rm -f "components/courses/LevelSelection.tsx"
rm -f "components/courses/PlacementTestModal.tsx"
rm -f "components/dashboard/AchievementCard.tsx"
rm -f "components/dashboard/CompletionTracker.tsx"
rm -f "components/dashboard/CourseProgress.tsx"
rm -f "components/dashboard/DailyStreakCard.tsx"
rm -f "components/dashboard/InitialCourseSetup.tsx"
rm -f "components/dashboard/LearningProgress.tsx"
rm -f "components/dashboard/LoadingSkeleton.tsx"
rm -f "components/dashboard/ProgressChart.tsx"
rm -f "components/dashboard/ProgressSection.tsx"
rm -f "components/dashboard/TaskProgressCard.tsx"
rm -f "components/dashboard/WelcomeBanner.tsx"
rm -f "components/debug/DebugOverlay.tsx"
rm -f "components/exercises/BaseExercise.tsx"
rm -f "components/exercises/ChatbotExercise.tsx"
rm -f "components/exercises/DebateExercise.tsx"
rm -f "components/exercises/ErrorCorrectionExercise.tsx"
rm -f "components/exercises/ExerciseContainer.tsx"
rm -f "components/exercises/FillInBlankExercise.tsx"
rm -f "components/exercises/GrammarExercise.tsx"
rm -f "components/exercises/ListeningExercise.tsx"
rm -f "components/exercises/MatchingExercise.tsx"
rm -f "components/exercises/MultipleChoiceExercise.tsx"
rm -f "components/exercises/PronunciationExercise.tsx"
rm -f "components/exercises/ReadingExercise.tsx"
rm -f "components/exercises/ScenarioExercise.tsx"
rm -f "components/exercises/SentenceTransformationExercise.tsx"
rm -f "components/exercises/ShortAnswerExercise.tsx"
rm -f "components/exercises/SpeakingExercise.tsx"
rm -f "components/exercises/VerbConjugationExercise.tsx"
rm -f "components/exercises/VocabularyExercise.tsx"
rm -f "components/exercises/WritingExercise.tsx"
rm -f "components/FillInBlankExercise.tsx"
rm -f "components/FixedMatchingExercise.tsx"
rm -f "components/Footer.tsx"
rm -f "components/GrammarChat.tsx"
rm -f "components/GrammarConjugator.tsx"
rm -f "components/GrammarExerciseTest.tsx"
rm -f "components/GrammarTutorContextual.tsx"
rm -f "components/HoverDefinition.tsx"
rm -f "components/Icon.tsx"
rm -f "components/IntroCarousel.tsx"
rm -f "components/layouts/DashboardLayout.tsx"
rm -f "components/MatchingExercise.tsx"
rm -f "components/MobileGrammarChat.tsx"
rm -f "components/MobileSentenceBuilder.tsx"
rm -f "components/MobileVocabularyChat.tsx"
rm -f "components/ModernChatbot.tsx"
rm -f "components/NavigationMenu.tsx"
rm -f "components/Navbar.tsx"
rm -f "components/PassageRenderer.tsx"
rm -f "components/pronunciation/PronunciationConversation.tsx"
rm -f "components/pronunciation/PronunciationConversationV2.tsx"
rm -f "components/pronunciation/PronunciationConversationV3.tsx"
rm -f "components/pronunciation/PronunciationConversationV4.tsx"
rm -f "components/pronunciation/PronunciationList.tsx"
rm -f "components/pronunciation/pronunciation-practice.tsx"
rm -f "components/QuestionRenderer.tsx"
rm -f "components/reading/AssignmentBadge.tsx"
rm -f "components/reading/AssignmentBanner.tsx"
rm -f "components/reading/InstructionsModal.tsx"
rm -f "components/reading/ReadingComprehensionTest.tsx"
rm -f "components/reading/ReadingPracticeTest.tsx"
rm -f "components/reading/ReadingQuiz.tsx"
rm -f "components/reading/ReadingTest.tsx"
rm -f "components/reading/ReadingTestTimed.tsx"
rm -f "components/reading/ScoringGuide.tsx"
rm -f "components/results/SpeakingResults.tsx"
rm -f "components/SentenceBuilder.tsx"
rm -f "components/SentenceBuilderMobile.tsx"
rm -f "components/SentenceBuilderTest.tsx"
rm -f "components/sidebar.tsx"
rm -f "components/speaking/SpeakingConversation.tsx"
rm -f "components/speaking/SpeakingConversationV2.tsx"
rm -f "components/speaking/SpeakingConversationV3.tsx"
rm -f "components/speaking/SpeakingList.tsx"
rm -f "components/TimedMatchingExercise.tsx"
rm -f "components/UserMetrics.tsx"
rm -f "components/vocabulary-chat-mobile.tsx"
rm -f "components/VocabularyChat.tsx"
rm -f "components/VocabularyLearningChart.tsx"
rm -f "components/VocabularyPreview.tsx"
rm -f "components/VocabularyTable.tsx"
rm -f "components/WordTransition.tsx"

rm -f "contexts/DashboardDataContext.tsx"

rm -f "data/papers.ts"

rm -f "hooks/useAssessment.ts"
rm -f "hooks/useAzureRealtimeAPI.ts"
rm -f "hooks/useChatAndTranscription.ts"
rm -f "hooks/useCombinedTranscriptions.ts"
rm -f "hooks/useConnectionDetails.ts"
rm -f "hooks/useDebug.ts"
rm -f "hooks/useEnrollment.ts"
rm -f "hooks/useEnrollmentCount.ts"
rm -f "hooks/useExerciseData.ts"
rm -f "hooks/useLessonData.ts"
rm -f "hooks/useLocalMicTrack.ts"
rm -f "hooks/useMediaQuery.ts"
rm -f "hooks/usePronunciationData.ts"
rm -f "hooks/useQuestionFeedback.ts"
rm -f "hooks/useQuestionScoring.ts"
rm -f "hooks/useSpeakingPipelineStreamingSTT.ts"
rm -f "hooks/useTrackVolume.ts"

rm -f "lib/api-client.ts"
rm -f "lib/api-performance.ts"
rm -f "lib/assessments.ts"
rm -f "lib/audio-conversion-api.ts"
rm -f "lib/audio-converter-serverless.ts"
rm -f "lib/audio-converter.ts"
rm -f "lib/auth-helpers.ts"
rm -f "lib/azure-audio-service.ts"
rm -f "lib/azure-openai-rate-limiter.ts"
rm -f "lib/errors.ts"
rm -f "lib/exercise-routing.ts"
rm -f "lib/get-base-url.ts"
rm -f "lib/hooks/useEvaluateAnswers.ts"
rm -f "lib/interfaces.ts"
rm -f "lib/livekit-types.ts"
rm -f "lib/livekit-utils.ts"
rm -f "lib/materials-pronunciation.ts"
rm -f "lib/posthog.ts"
rm -f "lib/pronunciation-helper.ts"
rm -f "lib/realtime/websocket-relay.ts"
rm -f "lib/schemas/questions-only.ts"
rm -f "lib/teacher-assignment-assistant.ts"
rm -f "lib/teacher-assistant-examples.ts"
rm -f "lib/types.ts"
rm -f "lib/vocabularyManager.ts"
rm -f "lib/whatsapp-tts.ts"
rm -f "lib/writing-eval.js"
rm -f "lib/writing.js"

rm -f "livekit-app-config.ts"
rm -f "middleware-2024.ts"
rm -f "middleware-old.ts"
rm -f "middleware-rbac.ts"

rm -f "test-azure-ai.js"
rm -f "test-context.js"
rm -f "test-worksheet-content.js"

rm -f "utils/germanCommonWords.ts"
rm -f "utils/readingApiTemplate.ts"

# Remove empty directories
find . -type d -empty -delete 2>/dev/null || true

echo "Dead code removal complete!"
echo "You may want to review the changes before committing."
